protocol file
mime inode/directory
action launch --type=background tmux send-keys "cd ${FILE_PATH}" Enter

protocol file
mime image/*,video/*,audio/*
action launch --type=background open -R "${FILE_PATH}"

protocol file
action launch --type=background tmux run-shell "~/.local/bin/launch-editor-script.sh ${FILE_PATH}"
