M = {
  File = { icon = " ", navic_hl = "NavicIconsFile", hl = "CmpItemKindFile" },
  Module = { icon = " ", navic_hl = "NavicIconsModule", hl = "CmpItemKindClass" },
  Namespace = { icon = " ", navic_hl = "CmpItemKindClassNavicIconsNamespace", hl = "CmpItemKindClass" },
  Package = { icon = " ", navic_hl = "NavicIconsPackage", hl = "CmpItemKindProperty" },
  Class = { icon = " ", navic_hl = "CmpItemKindClassNavicIconsClass", hl = "CmpItemKindClass" },
  Method = { icon = " ", navic_hl = "NavicIconsMethod", hl = "CmpItemKindMethod" },
  Property = { icon = " ", navic_hl = "NavicIconsProperty", hl = "CmpItemKindProperty" },
  Field = { icon = " ", navic_hl = "NavicIconsField", hl = "CmpItemKindField" },
  Constructor = { icon = " ", navic_hl = "NavicIconsConstructor", hl = "CmpItemKindConstructor" },
  Enum = { icon = " ", navic_hl = "NavicIconsEnum", hl = "CmpItemKindValue" },
  Interface = { icon = " ", navic_hl = "NavicIconsInterface", hl = "CmpItemKindInterface" },
  Function = { icon = " ", navic_hl = "NavicIconsFunction", hl = "CmpItemKindFunction" },
  Variable = { icon = " ", navic_hl = "NavicIconsVariable", hl = "CmpItemKindVariable" },
  Constant = { icon = " ", navic_hl = "NavicIconsConstant", hl = "CmpItemKindVariable" },
  String = { icon = " ", navic_hl = "NavicIconsString", hl = "CmpItemKindText" },
  Number = { icon = " ", navic_hl = "NavicIconsNumber", hl = "CmpItemKindValue" },
  Boolean = { icon = " ", navic_hl = "NavicIconsBoolean", hl = "CmpItemKindValue" },
  Array = { icon = " ", navic_hl = "NavicIconsArray", hl = "CmpItemKindVariable" },
  Object = { icon = " ", navic_hl = "NavicIconsObject", hl = "CmpItemKindVariable" },
  Key = { icon = " ", navic_hl = "NavicIconsKey", hl = "CmpItemKindKeyword" },
  Null = { icon = " ", navic_hl = "NavicIconsNull", hl = "TSNone" },
  EnumMember = { icon = " ", navic_hl = "NavicIconsEnumMember", hl = "CmpItemKindVariableCmpItemKindFile" },
  Struct = { icon = " ", navic_hl = "NavicIconsStruct", hl = "CmpItemKindStruct" },
  Event = { icon = " ", navic_hl = "NavicIconsEvent", hl = "CmpItemKindEvent" },
  Operator = { icon = " ", navic_hl = "NavicIconsOperator", hl = "CmpItemKindOperator" },
  TypeParameter = { icon = " ", navic_hl = "NavicIconsTypeParameter", hl = "CmpItemKindTypeParameter" },
}

return M
