#!/usr/bin/env osascript
# Returns the current playing song in Spotify for OSX

tell application "Spotify"
  if it is running then
    if player state is playing then
      set track_name_dirty to name of current track
      set artist_name_dirty to artist of current track
      set command_string to "echo \"" & artist_name_dirty & "\" | perl -pne 's/(,|\\s[\\(-]|\\sft\\.\\s).+$//'" as string
      set artist_name to do shell script command_string
      set command_string to "echo \"" & track_name_dirty & "\" | perl -pne 's/(,|\\s[\\(-]|\\sft\\.\\s).+$//'" as string
      set track_name to do shell script command_string

      if artist_name > 0
        # If the track has an artist set and is therefore most likely a song rather than an advert
        "   " & artist_name & " - " & track_name # & " #[bg=black] #[bg=colour234]"
      else
        # If the track doesn't have an artist set and is therefore most likely an advert rather than a song
        "~ " & track_name
      end if
    end if
  end if
end tell
