-- Winbar breadcrumps navigator config
require("nvim-navic").setup({
  highlight = true,
  separator = " › ",
  depth_limit = 5,
  icons = {
    File = " ",
    Module = " ",
    Namespace = " ",
    Package = " ",
    Class = " ",
    Method = " ",
    Property = " ",
    Field = " ",
    Constructor = " ",
    Enum = " ",
    Interface = " ",
    Function = " ",
    Variable = " ",
    Constant = " ",
    String = " ",
    Number = " ",
    Boolean = " ",
    Array = " ",
    Object = " ",
    Key = " ",
    Null = " ",
    EnumMember = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
})
vim.api.nvim_set_hl(0, "NavicIconsFile", { link = "CmpItemKindFile" })
vim.api.nvim_set_hl(0, "NavicIconsModule", { link = "CmpItemKindClass" })
vim.api.nvim_set_hl(0, "NavicIconsNamespace", { link = "CmpItemKindClass" })
vim.api.nvim_set_hl(0, "NavicIconsPackage", { link = "CmpItemKindProperty" })
vim.api.nvim_set_hl(0, "NavicIconsClass", { link = "CmpItemKindClass" })
vim.api.nvim_set_hl(0, "NavicIconsMethod", { link = "CmpItemKindMethod" })
vim.api.nvim_set_hl(0, "NavicIconsProperty", { link = "CmpItemKindProperty" })
vim.api.nvim_set_hl(0, "NavicIconsField", { link = "CmpItemKindField" })
vim.api.nvim_set_hl(0, "NavicIconsConstructor", { link = "CmpItemKindConstructor" })
vim.api.nvim_set_hl(0, "NavicIconsEnum", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsInterface", { link = "CmpItemKindInterface" })
vim.api.nvim_set_hl(0, "NavicIconsFunction", { link = "CmpItemKindFunction" })
vim.api.nvim_set_hl(0, "NavicIconsVariable", { default = true, link = "CmpItemKindVariable" })
vim.api.nvim_set_hl(0, "NavicIconsConstant", { link = "CmpItemKindVariable" })
vim.api.nvim_set_hl(0, "NavicIconsString", { link = "CmpItemKindText" })
vim.api.nvim_set_hl(0, "NavicIconsNumber", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsBoolean", { link = "CmpItemKindValue" })
vim.api.nvim_set_hl(0, "NavicIconsArray", { link = "CmpItemKindVariable" })
vim.api.nvim_set_hl(0, "NavicIconsObject", { link = "CmpItemKindVariable" })
vim.api.nvim_set_hl(0, "NavicIconsKey", { link = "CmpItemKindKeyword" })
vim.api.nvim_set_hl(0, "NavicIconsNull", { link = "TSNone" })
vim.api.nvim_set_hl(0, "NavicIconsEnumMember", { link = "CmpItemKindVariable" })
vim.api.nvim_set_hl(0, "NavicIconsStruct", { link = "CmpItemKindStruct" })
vim.api.nvim_set_hl(0, "NavicIconsEvent", { link = "CmpItemKindEvent" })
vim.api.nvim_set_hl(0, "NavicIconsOperator", { link = "CmpItemKindOperator" })
vim.api.nvim_set_hl(0, "NavicIconsTypeParameter", { link = "CmpItemKindTypeParameter" })
vim.api.nvim_set_hl(0, "NavicText", { link = "Comment" })
vim.api.nvim_set_hl(0, "NavicSeparator", { link = "WhiteSpace" })
