require("plugins")
require("plugin_config")
require("base")
require("mappings")
require("lsp")
require("lsp.lua-ls")
require("lsp.typescript-ls")

vim.cmd("source ~/.config/nvim/mappings.vim")
vim.cmd("source ~/.config/nvim/extra.vim")
